### ISSUE TITLE
AbstractFactory - how does it know which WriterFactory to return

### ISSUE THREAD

**Issue by alexkb** [DesignPatternsPHP/DesignPatternsPHP#421]
In the [AbstractFactory](https://github.com/DesignPatternsPHP/DesignPatternsPHP/tree/main/Creational/AbstractFactory) example, I'm curious where the concrete class of WriterFactory.php is located. i.e. where is the code that determines if the factory should return the Windows WriterFactory or the Unix WriterFactory. Apologies if this is obvious, I just couldn't find it. Thank you.

**Comment by domnikl** [comment]
Hey @alexkb! It's not obvious because it's not here. The client code would decide that and so it's simply not implemented here. You could do that with a Strategy pattern or with a simple if-else in the code.
