### ISSUE TITLE
composer install  - FAIL

### ISSUE THREAD

**Issue by a1812** [DesignPatternsPHP/DesignPatternsPHP#426]
```
$ git clone https://github.com/DesignPatternsPHP/DesignPatternsPHP.git
$ cd DesignPatternsPHP
$ composer install
```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ocramius/package-versions is locked to version 1.7.0 and an update of this package was not requested.
    - ocramius/package-versions 1.7.0 requires composer-plugin-api ^1.1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - ocramius/package-versions 1.7.0 requires composer-plugin-api ^1.1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - vimeo/psalm 3.10.1 requires ocramius/package-versions ^1.2 -> satisfiable by ocramius/package-versions[1.7.0].
    - vimeo/psalm is locked to version 3.10.1 and an update of this package was not requested.

ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by a1812** [comment]
complete in PR https://github.com/DesignPatternsPHP/DesignPatternsPHP/pull/428

**Comment by domnikl** [comment]
Thank you for the issue and the fix, I merged it in.
