### ISSUE TITLE
Translation error in readthedocs

### ISSUE THREAD

**Issue by ajest** [DesignPatternsPHP/DesignPatternsPHP#437]
It seems like the translations are not working well in the spanish version, ie https://designpatternsphp.readthedocs.io/es/latest/Creational/AbstractFactory/README.html

![Captura de pantalla 2021-06-14 a la(s) 11 00 49](https://user-images.githubusercontent.com/4982093/121904988-0dca7c00-cd00-11eb-8922-65625b656680.png)

**Comment by domnikl** [comment]
Hi @ajest, that is because the original text has been changed and there isn't yet a new translation. Unfortunately I don't speak spanish. I'd be happy to merge a PR for this though :)

**Comment by manueldose** [comment]
Hi @domnikl  I'm really new to the world of open source and public relations, I would like to help with the Spanish translations. How do I proceed? Which are the files that I should modify the README.md or the README.rst
