### ISSUE TITLE
use standard coding style from PHP Code Sniffer

### ISSUE THREAD

**Issue by domnikl** [DesignPatternsPHP/DesignPatternsPHP#444]
Right now, the FLYERALARM coding style is being used, instead the standard coding style from Code Sniffer should be used. With that, the dep on `flyeralarm/php-code-validator` can be removed.

**Comment by leonhusmann** [comment]
Hi, I would like to work on this issue. When you're referencing to the "standard" coding style from Code Sniffer you mean "PEAR" right? Just to make sure I'm not applying the wrong standard.

When I get you right your desired `phpcs.xml.dist` would look like this right?
```
<?xml version="1.0" encoding="UTF-8" ?>
<ruleset name="Project Rules">
    <directory>**/*.php</directory>
    <exclude-pattern>vendor</exclude-pattern>
    <arg value="sp"/>

    <!-- Include the whole PEAR standard -->
    <rule ref="PEAR">
        <exclude name="PEAR.NamingConventions.ValidFunctionName"/>
        <exclude name="PEAR.NamingConventions.ValidVariableName"/>
        <exclude name="PEAR.Commenting.ClassComment"/>
        <exclude name="PEAR.Commenting.FileComment.MissingCategoryTag"/>
        <exclude name="PEAR.Commenting.FileComment.MissingPackageTag"/>
        <exclude name="PEAR.Commenting.FileComment.MissingLinkTag"/>
        <exclude name="PEAR.Commenting.FileComment.MissingVersion"/>
        <exclude name="PEAR.Commenting.InlineComment"/>
    </rule>
</ruleset>
```

**Comment by domnikl** [comment]
Hi @leonhusmann, thanks for working on it! I'd much rather ditch the config entireley (if possible) and just use the PSR12 standard.

**Comment by mariosimao** [comment]
I've created a PR adopting the PSR-12 standard
