### ISSUE TITLE
Incomplete translation to Brazilian Portuguese 

### ISSUE THREAD

**Issue by raphaeldealmeida** [DesignPatternsPHP/DesignPatternsPHP#465]
As I studied the guide I noticed that some parts of it were not fully translated into Brazilian Portuguese.

I did a review and found the following pages that need improvement:
https://designpatternsphp.readthedocs.io/pt_BR/latest/Structural/DependencyInjection/README.html#
https://designpatternsphp.readthedocs.io/pt_BR/latest/Structural/Facade/README.html
https://designpatternsphp.readthedocs.io/pt_BR/latest/Behavioral/Interpreter/README.html#

**Comment by domnikl** [comment]
Closing as it is already merged. Thanks @raphaeldealmeida!
