### ISSUE TITLE
strategy pattern php

### ISSUE THREAD

**Issue by jamielsharief** [DesignPatternsPHP/DesignPatternsPHP#472]
I am Googling `strategy pattern php` and don't see my favourite resource on design patterns (your website). 

I suggest looking at adding some important keywords to pages , perhaps some breadcrumbs can help (link juice with important keywords), and maybe adding spaces to `DesignPatternsPHP` to ensure those keywords are picked up.

**Comment by domnikl** [comment]
Hi @jamielsharief, great to hear that you like it 😃 
I am by far no expert in SEO, I added some meta keywords and will be working on each page later on when I've got more time. Hopefully that will improve search engine ranking. Thanks for your input on this!
