### ISSUE TITLE
Project marked as spam

### ISSUE THREAD

**Issue by CnTripto** [DesignPatternsPHP/DesignPatternsPHP#498]
document on readthedoc can't access already

**Comment by w3lifer** [comment]
@CnTripto, support response from "Read the Docs":

> This project was marked as spam after a user forked the design patterns documentation, edited the project to contain spam links, and then added the new fork to Read the Docs under the old project name that the design patterns documentation had previously used. I'm not sure why the project still links to the Read the Docs project that they are not using though. I would reach out to the maintainers to resolve this.

🤔

**Comment by BorislavSabev** [comment]
@w3lifer where is the support thread?

**Comment by BorislavSabev** [comment]
I've contacted support and will be resolving the matter.

**Comment by BorislavSabev** [comment]
The issue has been resolved.

https://designpatternsphp.readthedocs.io/
