### ISSUE TITLE
 How to translate languages from other countries 

### ISSUE THREAD

**Issue by linjialiang** [DesignPatternsPHP/DesignPatternsPHP#500]
>  How to translate languages from other countries

**Comment by BorislavSabev** [comment]
You can easily add a translation by adding the required `locale` folder & files structure. 
However I would advise against that at the current moment as we are considering dropping the multiple language support. 

The main problem is that people who do translations generally do it once and forget about it. However this repository is evolving and is changing constantly. Thus the translations are lagging behind the original English version.
