### ISSUE TITLE
*

### ISSUE THREAD

**Issue by KaliSama666** [DesignPatternsPHP/DesignPatternsPHP#506]
https://home.nest.com/login/nest?local_next=%2Foauth2%3Fresponse_type%3Dcode%26client_id%3D744020a6-cee3-4e5a-9a6c-b728e9109b0b%26redirect_uri%3Dhttps%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fnest-home-assistant-prod%26state%3DAPvkAzEjSGz_FnSJ5kJ0JlENgNUWuPX4uMbKP5PDscvu-ahk00W8Es-pxaT_EqNT09zqd7KZxsOzK-vv73JWg9d9cIOkVnfhE4firZJEFaC2UYc3oKlADQQ00dNmIymXKP4vGAtt-_GOrpDY0QRenqXvFcfn01Gq2zj3XytHxLvXwYxPksJOIE7GeRyus_lOSKrxNgUc2Kpqj0AeXCcBr6hoXvB_eZtbdvkgY8lxU-UfFKqTirzQIoEmXHbDiXsY6T73GUicnG8KpxodsfBV-yphOmqadDxMuYdg0gH5Z5RN3qncEwefKNLMY4toYMnVr7-644DOKYcNBQMSVrc2pYKVXdWZqtp8qWoi7GmEzprme_z5Om9DH-9mGjh121leQCjnFakmuaI8ru-3Ug5KWNEtV6hoLFQyBPtfXh7AMeiCoSKBrsj_srNxwKfQam9IQPrdosBRxAR1WeXkl0wyt9sx3bWYK3VT0zamaznDJe-4Hr1DfxOyAGHLPrnHjK2DjPprbGHQtYJHgcQCjWFKUhA0b8mXirvMwtMPhiee3Pui1xNQ&style=oauth

**Comment by BorislavSabev** [comment]
Closing as spam
